config/routes.rb
Messageboard::Application.routes.draw do
  devise_for :users
  resources :messages

  root "messages#index"
  get "about" => "pages#about"

end

app/models/message.rb
class Message < ActiveRecord::Base

	
	belongs_to :user
	validates :message, presence: true
	validates_presence_of :name
	

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :messages, dependent: :nullify

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :default_url => "/images/:style/missing.png" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :avatar
   end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :set_message, only: [ :show, :edit , :update , :destroy]
	before_action :correct_user, only: [:edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	

	def index
		@messages = Message.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 3)
	end

	def show
	end

	def new
		#@message = Message.new
		@message = current_user.messages.build
	end

	def create
		
		#@message = Message.new(message_params)
		@message = current_user.messages.build(message_params)

		if(@message.save)
			redirect_to message_path(@message)
		else
			render action: 'new'
		end
	end

	def edit
	end

	def update
		if(@message.update(message_params))
			redirect_to message_path(@message)
		else
			render action: 'edit'
		end
	end

	def destroy
		if(@message.present?)
			@message.destroy
		end	
		redirect_to messages_path
		

	end

	private

		def set_message
			@message = Message.find(params[:id])
		end

				#防止別結透過網址入侵，修改別人的message
		def correct_user		
      	@message = current_user.messages.find_by_id(params[:id])
      	redirect_to messages_path, notice: "Not authorized to edit this message" if @message.nil?
    end

		def message_params
			params.require(:message).permit(:name , :message)
		end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end



  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">SimpleProject</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li> 

      <%if(user_signed_in?)%>
       <li><%= link_to "Acount setting" , edit_user_registration_path%></li>

        <li><%= link_to 'new', new_message_path %><li>

        <li><%= link_to "Log out", destroy_user_session_path , method: :delete%></li> 
      <%else%>
        <li><%= link_to "Sign in", new_user_session_path %></li> 
        <li><%= link_to "Sign up", new_user_registration_path %></li> 
      <%end%>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageboardV2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  

  <%= render 'layouts/header'%>

  <div class="container">
  	<!--<div class="well">-->
      <%flash.each do |name,msg|%>

        <%=content_tag(:div, msg , class: "alert alert-info alert#{name}")%>
      <%end%>
   		<%= yield %>
    <!--</div>-->
  </div>


</body>
</html>

app/views/messages/_form.html.erb
<div class="well">
<%= form_for @message do |f| %>
	<% if(@message.errors.any?) %>
		<div id="error_explanation">
			<h2><%= pluralized(@message.error.count , "error") %> prohibited this messge being saved:</h2>
			<ul>
				<%= @message.errors.full_message.each do |msg|%>
					<li><%= msg%></li>
				<% end %>
			</ul>

		</div>
	<%end%>

	<div class="form-group">
		<%=f.label(:name, 'Named')%>
		<%=f.text_field(:name , class: "form-control")%>
	</div>

	<div class="form-group">
		<%=f.label(:message)%>
		<%=f.text_area(:message , class: "form-control") %>
	</div>

	 <div class="form-group">
    <%= f.submit(class: "btn btn-primary") %>
  </div>


<%end%>
</div>

app/views/messages/edit.html.erb
<p>Edit</p>

<%=render 'form'%>

<%=link_to 'back to index' , messages_path%>

app/views/messages/index.html.erb
<%= render 'pages/home'  unless user_signed_in?%>


	<% @messages.each do |message| %>

		<div class="row">
			<div class="col-md-12 well">
				<h4><%= message.name %></h4>
				<%= simple_format(message.message)%>

				<%= image_tag message.user.avatar.url(:medium) %>

				<p><%= message.user_id%><p>

				<p><%= message.user.email if(message.user)%><p>
	
					
				<!--<h5><%= message.message %></h5>-->

				<%= link_to 'show', message_path(message) %>
				<%if(message.user == current_user)%>
					<%= link_to 'edit', edit_message_path(message) %>
					<%= link_to 'delete', message_path(message),method: :delete, data: { confirm: 'Are you sure?' } %>
					<!--<%= button_to 'delete', message_path(message), method: :delete%>-->
				<%end%>
			</div>
		</div>



	<% end %>
		

<div class="row">
	<div class="col-md-12 ">
		<% if user_signed_in?%>
			<%= link_to 'new', new_message_path %>
		<%end%>
	</div>
</div>


<div class="center">
 	<%= will_paginate @posts, renderer: BootstrapPagination::Rails %>
</div>

app/views/messages/new.html.erb
<p>New</p>
<%= render 'form'%>
<%= link_to 'Back' , messages_path%>

app/views/messages/show.html.erb
<p>Show</p>
<div class="coantiner">
	<div class= "well">
		<h4><%= @message.name %></h4>
		<h5><%= simple_format(@message.message) %></h5>

	</div>
</div>

<%=link_to messages_path do%>
	<span class="glyphicon glyphicon-trash"></span>Back
<%end%>

app/views/pages/_home.html.erb
<h1>Please Sign in~~~~~~~~~~</h1>


<!--
<p>Find me in app/views/pages/home.html.erb</p>
<h1>Welcome to messageboard<h1>
<%= link_to "Home" ,root_path%>
<%= link_to "About" ,about_path%>

-->
<!--
<div class="row">
	<div class="col-md-4">
-->
		<!--<img class="" src="https://dl.dropboxusercontent.com/u/247736432/small_201012081233145529.jpg" alt="..."></img>-->
<!--		
		<h1>Welcome to messageboard<h1>
	</div>

	<div class="col-md-4">
		<h1>Welcome to messageboard<h1>
	</div>

	<div class="col-md-4">
		<h1>Welcome to messageboard<h1>
	</div>


</div>
-->

app/views/pages/about.html.erb
<h1>Pages#home</h1>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<h1>Welcome to messageboard<h1>
<%= link_to "Home" ,root_path%>
<%= link_to "About" ,about_path%>

<div class="row">
	<div class="col-md-4">
		<!--<img class="" src="https://dl.dropboxusercontent.com/u/247736432/small_201012081233145529.jpg" alt="..."></img>-->
		<h1>Welcome to messageboard<h1>
	</div>

	<div class="col-md-4">
		<h1>Welcome to messageboard<h1>
	</div>

	<div class="col-md-4">
		<h1>Welcome to messageboard<h1>
	</div>


</div>